name: Node CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [develop]

defaults:
  run:
    working-directory: ./server

jobs:
  run-yarn-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yarn install and build webpack
        run: |
          yarn install
          yarn build
      - uses: actions/upload-artifact@main
        with:
          name: webpack artifacts
          path: ./dist/

  # build-node:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Node.js 12.x
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 12.x
  #     - name: Get npm cache directory
  #       id: npm-cache
  #       run: |
  #         echo "::set-output name=dir::$(npm config get cache)"
  #     - uses: actions/cache@v1
  #       with:
  #         path: ${{ steps.npm-cache.outputs.dir }}
  #         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
  #         restore-keys: |
  #           ${{ runner.os }}-node-
  #     - name: npm install, build, and test
  #       run: |
  #         npm ci
  #         npm run build --if-present
  #       env:
  #         CI: true
